export const authConstants = {
  CATEGORY : 'CATEGORY',
  PRODUCT : 'PRODUCT',
  TYPE : 'TYPE',
  ACCOUNT : 'ACCOUNT',
  LOGIN : 'LOGIN',
  STATUS_LOGIN : 'STATUS_LOGIN',
  CART : 'CART',
  QUESTION : 'QUESTION'
};
